### ISSUE TITLE
Optimizer: 表达式内部优化

### ISSUE THREAD

**Issue by Fuyuky** [rrvm-project/SysYc#37]
AST 生成时，同优先级运算符为左结合，例如 `1+a+2` 会做成 `(1+a)+2`，如果能重新排列成 `(1+2)+a` 的话，就可以在常量折叠等后续步骤中进行优化；若有两个表达式 `(a+b)+c` 和 `(a+c)+d`，将第一个重排成 `(a+c)+b` 也可以在 svn 等步骤中产生优化。
因此，对表达式内部的项进行重排有助于后续的优化工作进行，还有“树高平衡”等应当归属于这个优化器的优化。

请 assignee 思考：
1. 这个优化应当放在哪个部分？前端 AST 生成后？生成时？中端的新 pass？
2. 达成的效果应当是什么？
3. 具体的优化策略。

开始实现前在此 issue 下回答这三个问题。

**Comment by Lethe10137** [comment]
1 中端新pass
2和3  
在一个基本块内， 对于i32类型的加减法、乘法，
寻找能apply交换律的最大的边界，
如2 + a + c + 3 + b + 4
1 先把常量折叠成一个点
2 再排成 9 + a + b + c (不知道常量的temp，给一个全序，例如其自身的排序)
3 排成一个尽量平衡的树
