### ISSUE TITLE
complete grammer of floating constants & interger constants

### ISSUE THREAD

**Issue by Fuyuky** [rrvm-project/SysYc#4]
参考[文档](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1124.pdf)的 54 ~ 58 页，实现完备的整数、浮点数字面量文法。

**Comment by GitPinkRabbit** [comment]
你的编译器会打总力战吗

**Comment by Nikaidou-Shinku** [comment]
> 你的编译器会打总力战吗

Fuyuki 编译器上期总力战一档。

**Comment by Rosayxy** [comment]
收到~

**Comment by Azure-stars** [comment]
看看 fuyuki 的大决战排名
