### ISSUE TITLE
在中端优化过程中如何实现创建不重复新 Temp

### ISSUE THREAD

**Issue by cyh2004** [rrvm-project/SysYc#64]
现在强度削弱的 pass 有创建新 temp 的需求，但是我们没有直接的方法创建不重复的新 Temp。

现在我的解决方案是，在创建新 temp 时给名字加上 suffix，比如“_osr"（OSR 是强度削弱那个算法的名称），这样可以避免与已有的temp重复
此外，在最外层的Optimizer1类中记录一个成员变量 total_new_temp_osr，记录强度削弱这一步总共创建了多少个变量，这样可以避免在多次执行同一 pass 时，与上一次创建的变量重复

但这样并没有扩展性，每个 pass 都相当于得给自己实现个 temp manager

**Comment by Fuyuky** [comment]
可以将 TempManager 挪到 RrvmProgram 中
