### ISSUE TITLE
启用全部测例 & 使用 gcc -O2 作为性能测试基准

### ISSUE THREAD

**Issue by Fuyuky** [rrvm-project/SysYc#89]
如题，现在的性能测试只包含了完整版性能测试中的一小部分，当能通过全部测例时应当开始使用全部测例。

此外，目前的性能测试基准为 gcc -O2 的 0.8 倍，之后应使用 gcc -O2 的 1.0 倍为性能测试基准。

**Comment by Nikaidou-Shinku** [comment]
阿伟哦，还在写编译器啊，休息一下好不好

**Comment by Fuyuky** [comment]
> 阿伟哦，还在写编译器啊，休息一下好不好

你来帮我瞅瞅这**玩意，那个一千个参数的点还是不能跑

**Comment by Fuyuky** [comment]
算了放弃了，那个千把变量互相依赖到死的点跑不出来，先不要了。

加上尾递归优化后能跑过 median2，剩下那仨得把后端炸了重写，先不要了。
