### ISSUE TITLE
测试时个别测例没有 gcc 生成的汇编，可执行文件和 stdout

### ISSUE THREAD

**Issue by cyh2004** [rrvm-project/SysYc#91]
拎出如下测例到 ../tmp 文件夹下
![image](https://github.com/rrvm-project/SysYc/assets/50762765/f323e719-f74c-4050-8305-fe16fea5d656)

运行 `python test.py -t ../tmp -b`

build 文件夹内容如下
![c432dc7e4cdfc62dc6cc70dcd6f8673](https://github.com/rrvm-project/SysYc/assets/50762765/be87e913-57c4-4efe-a2d6-39181d6a2d7d)
命令行信息如下
![9dea1533e4189fc4a37818679437599](https://github.com/rrvm-project/SysYc/assets/50762765/8f1aba30-2df1-4392-b60b-d921af75e9be)
有两个测例没有 gcc 生成的文件

**Comment by cyh2004** [comment]
并且反复执行 `python test.py -t ../tmp -b` 还会有不一样的结果，偶尔 fft2 测例能够获得 gcc 产生的文件

**Comment by cyh2004** [comment]
这种现象在 github workflow 中似乎也存在，在 strength 分支的最新 commit 中

**Comment by cyh2004** [comment]
噢好像是我自己的问题

**Comment by Fuyuky** [comment]
没事我就关了
